'use strict';
/**
 * Firebase Cloud Function: generateQuestions
 * - Callable function that proxies requests to the DeepSeek Chat Completions API
 * - API key is stored securely via: firebase functions:config:set deepseek.key="YOUR_KEY"
 * - Inputs: { topic: string, count: number }
 * - Output: JSON string (strict JSON) as generated by the model
 */

const functions = require('firebase-functions');
const admin = require('firebase-admin');
const axios = require('axios').default;

// Initialize Admin SDK once
try {
  admin.app();
} catch (e) {
  admin.initializeApp();
}
const db = admin.firestore();

// Region and runtime options
const REGION = 'us-central1';
const RUNTIME_OPTS = { timeoutSeconds: 60, memory: '256MB' };

/**
 * Build the exact prompt required by the client.
 */
function buildPrompt(topic, count) {
  return `Generate questions for a student test.

Topic: ${topic}
Total Questions: ${count}

Distribute the questions evenly across these three types:
1. Multiple Choice Questions (MCQ)
2. True or False
3. Match the Following

Return the output in pure JSON format ONLY, with NO explanations, no markdown, and no extra text.

The JSON structure must be exactly:

{
  "mcq": [
    {
      "question": "Question text",
      "options": ["Option A", "Option B", "Option C", "Option D"],
      "answer": 0
    }
  ],
  "true_false": [
    {
      "question": "Question text",
      "answer": true
    }
  ],
  "match_the_following": [
    {
      "question": "Match the items",
      "left": ["Item1", "Item2", "Item3", "Item4"],
      "right": ["Match1", "Match2", "Match3", "Match4"],
      "answer": { "Item1": "Match2", "Item2": "Match1", "Item3": "Match4", "Item4": "Match3" }
    }
  ]
}

Rules:
- Output only valid JSON.
- Do not include explanations or notes.`;
}

/**
 * Sanitize potential code fences and ensure it's plain JSON text.
 */
function sanitizeToJsonString(text) {
  if (typeof text !== 'string') return '';
  let out = text.trim();
  // remove ```json ... ``` or ``` ... ``` fences if present
  if (out.startsWith('```')) {
    out = out.replace(/^```json\n?/i, '').replace(/^```\n?/i, '').replace(/```\s*$/i, '').trim();
  }
  return out;
}

/**
 * Basic structure validation to catch obvious format issues early.
 */
function validateStructure(obj) {
  if (!obj || typeof obj !== 'object') return false;
  if (!Array.isArray(obj.mcq) || !Array.isArray(obj.true_false) || !Array.isArray(obj.match_the_following)) return false;
  return true;
}

function buildMindmapPrompt({ topic, topicCount, depthLevel, learningStyle, subject, standard, section }) {
  const depthHint = (depthLevel === 'Deep' || depthLevel === 'Advanced')
    ? '3 to 4 levels'
    : depthLevel === 'Medium'
      ? '2 to 3 levels'
      : '1 to 2 levels';

  return `Create a classroom learning mindmap.
Topic: ${topic}
Subject: ${subject}
Standard: ${standard}
Section: ${section}
Main branches required: ${topicCount}
Depth level: ${depthLevel} (${depthHint})
Learning style: ${learningStyle}

Output STRICT JSON only (no markdown) in this schema:
{
  "topic": "${topic}",
  "branches": [
    {
      "title": "Branch title",
      "children": [
        {"title": "Child title", "children": []}
      ]
    }
  ]
}

Rules:
- Return valid JSON only.
- Keep titles concise (max 5 words each).
- Generate exactly ${topicCount} main branches.
- Keep branch names unique.
- Children must always be an array.
- No explanation text.`;
}

function normalizeMindmapNode(node) {
  if (!node || typeof node !== 'object') {
    return { title: 'Untitled', children: [] };
  }

  const title = String(node.title || '').trim() || 'Untitled';
  const childrenRaw = Array.isArray(node.children) ? node.children : [];
  const children = childrenRaw
    .filter((child) => child && typeof child === 'object')
    .map((child) => normalizeMindmapNode(child));

  return { title, children };
}

function normalizeMindmapStructure(aiJson, fallbackTopic) {
  const topic = String(aiJson?.topic || fallbackTopic || 'Mindmap').trim() || 'Mindmap';
  const branches = Array.isArray(aiJson?.branches)
    ? aiJson.branches.map((branch) => normalizeMindmapNode(branch)).filter((b) => b.title !== 'Untitled')
    : [];

  return {
    topic,
    root: {
      title: topic,
      children: branches,
    },
  };
}

exports.generateQuestions = functions
  .region(REGION)
  .runWith(RUNTIME_OPTS)
  .https.onCall(async (data, context) => {
    // Auth optional: you can restrict to authenticated teachers only if needed
    try {
      const topic = (data && data.topic ? String(data.topic) : '').trim();
      const count = Number(data && data.count);

      if (!topic) {
        throw new functions.https.HttpsError('invalid-argument', 'Missing required parameter: topic');
      }
      if (!Number.isInteger(count) || count < 3 || count > 100) {
        throw new functions.https.HttpsError('invalid-argument', 'Parameter "count" must be an integer between 3 and 100.');
      }

      const cfg = functions.config();
      const apiKey = cfg && cfg.deepseek && cfg.deepseek.key ? cfg.deepseek.key : '';
      if (!apiKey) {
        throw new functions.https.HttpsError(
          'failed-precondition',
          'DeepSeek API key is not set. Configure with: firebase functions:config:set deepseek.key="YOUR_KEY"'
        );
      }

      const prompt = buildPrompt(topic, count);

      // DeepSeek OpenAI-compatible endpoint
      const url = 'https://api.deepseek.com/v1/chat/completions';
      const payload = {
        model: 'deepseek-chat',
        messages: [
          { role: 'user', content: prompt }
        ],
        temperature: 0.7,
        max_tokens: 1800,
        // Enforce JSON-only output if supported
        response_format: { type: 'json_object' }
      };

      const headers = {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`
      };

      let response;
      try {
        response = await axios.post(url, payload, { headers, timeout: 30000 });
      } catch (err) {
        // Axios error handling
        const status = err.response ? err.response.status : null;
        const body = err.response ? err.response.data : null;
        console.error('DeepSeek API error', { status, body, message: err.message });
        if (status === 429) {
          throw new functions.https.HttpsError('resource-exhausted', 'Rate limited by DeepSeek API. Please retry later.');
        }
        if (status === 401 || status === 403) {
          throw new functions.https.HttpsError('permission-denied', 'Invalid DeepSeek API key or insufficient permissions.');
        }
        throw new functions.https.HttpsError('unavailable', 'Failed to reach DeepSeek API.');
      }

      if (!response || response.status < 200 || response.status >= 300 || !response.data) {
        throw new functions.https.HttpsError('internal', 'Unexpected response from DeepSeek API.');
      }

      const choices = response.data.choices;
      if (!choices || !Array.isArray(choices) || choices.length === 0) {
        throw new functions.https.HttpsError('internal', 'No choices returned by DeepSeek API.');
      }

      const contentRaw = choices[0]?.message?.content ?? '';
      const jsonText = sanitizeToJsonString(contentRaw);

      // Validate JSON parses
      let parsed;
      try {
        parsed = JSON.parse(jsonText);
      } catch (e) {
        console.error('JSON parse failed. Content:', jsonText);
        throw new functions.https.HttpsError('data-loss', 'Model returned invalid JSON. Please retry.');
      }

      // Basic structure validation
      if (!validateStructure(parsed)) {
        throw new functions.https.HttpsError('failed-precondition', 'Model returned JSON in unexpected structure.');
      }

      // Return the JSON STRING (as required) back to Flutter
      return JSON.stringify(parsed);
    } catch (error) {
      if (error instanceof functions.https.HttpsError) {
        throw error;
      }
      console.error('Unhandled error in generateQuestions:', error);
      throw new functions.https.HttpsError('internal', 'Unexpected error.');
    }
  });

exports.generateMindmap = functions
  .region(REGION)
  .runWith({ timeoutSeconds: 90, memory: '512MB' })
  .https.onCall(async (data, context) => {
    if (!context.auth?.uid) {
      throw new functions.https.HttpsError('unauthenticated', 'Authentication required.');
    }

    const uid = context.auth.uid;
    const classId = String(data?.classId || '').trim();
    const subjectId = String(data?.subjectId || '').trim();
    const topic = String(data?.topic || '').trim();
    const topicCount = Number(data?.topicCount);
    const depthLevel = String(data?.depthLevel || 'Medium').trim();
    const learningStyle = String(data?.learningStyle || 'Concept Based').trim();
    const previewOnly = data?.previewOnly === true;

    if (!classId || !subjectId || !topic) {
      throw new functions.https.HttpsError('invalid-argument', 'classId, subjectId and topic are required.');
    }
    if (!Number.isInteger(topicCount) || topicCount < 3 || topicCount > 8) {
      throw new functions.https.HttpsError('invalid-argument', 'topicCount must be an integer between 3 and 8.');
    }

    const userDoc = await db.collection('users').doc(uid).get();
    const userData = userDoc.data() || {};
    const userRole = String(userData.role || '').toLowerCase();
    if (userRole !== 'teacher') {
      throw new functions.https.HttpsError('permission-denied', 'Only teachers can generate mindmaps.');
    }

    const classDoc = await db.collection('classes').doc(classId).get();
    if (!classDoc.exists) {
      throw new functions.https.HttpsError('not-found', 'Class not found.');
    }

    const classData = classDoc.data() || {};
    const standard = String(classData.className || '').trim();
    const section = String(classData.section || '').trim();
    const subjects = classData.subjects;
    let subjectName = subjectId;
    if (Array.isArray(subjects)) {
      const found = subjects.find((s) => String(s || '').toLowerCase().replace(/\s+/g, '_') === subjectId.toLowerCase());
      if (found) {
        subjectName = String(found);
      }
    }

    const cfg = functions.config();
    const apiKey = cfg && cfg.deepseek && cfg.deepseek.key ? cfg.deepseek.key : '';
    if (!apiKey) {
      throw new functions.https.HttpsError(
        'failed-precondition',
        'DeepSeek API key is not set. Configure with: firebase functions:config:set deepseek.key="YOUR_KEY"'
      );
    }

    const prompt = buildMindmapPrompt({
      topic,
      topicCount,
      depthLevel,
      learningStyle,
      subject: subjectName,
      standard,
      section,
    });

    const url = 'https://api.deepseek.com/v1/chat/completions';
    const payload = {
      model: 'deepseek-chat',
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.4,
      max_tokens: 2800,
      response_format: { type: 'json_object' },
    };

    let response;
    try {
      response = await axios.post(url, payload, {
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${apiKey}`,
        },
        timeout: 45000,
      });
    } catch (err) {
      const status = err?.response?.status;
      if (status === 429) {
        throw new functions.https.HttpsError('resource-exhausted', 'AI rate limit reached. Please retry.');
      }
      throw new functions.https.HttpsError('unavailable', 'Failed to generate mindmap.');
    }

    const raw = response?.data?.choices?.[0]?.message?.content || '';
    const jsonText = sanitizeToJsonString(raw);

    let parsed;
    try {
      parsed = JSON.parse(jsonText);
    } catch (e) {
      throw new functions.https.HttpsError('data-loss', 'AI returned invalid JSON.');
    }

    const normalized = normalizeMindmapStructure(parsed, topic);
    const previewNodes = normalized.root.children.slice(0, 4).map((n) => n.title);
    const groupId = `${classId}_${subjectId}`;

    if (previewOnly) {
      return {
        topic: normalized.topic,
        previewNodes,
        structure: normalized.root,
        groupId,
      };
    }

    const mindmapRef = db.collection('group_mindmaps').doc();
    await mindmapRef.set({
      mindmap_id: mindmapRef.id,
      group_id: groupId,
      class_id: classId,
      subject_id: subjectId,
      standard,
      section,
      subject: subjectName,
      topic: normalized.topic,
      json_structure: normalized.root,
      created_by: uid,
      created_at: admin.firestore.FieldValue.serverTimestamp(),
      depth_level: depthLevel,
      learning_style: learningStyle,
      topic_count: topicCount,
    });

    return {
      mindmapId: mindmapRef.id,
      topic: normalized.topic,
      previewNodes,
      structure: normalized.root,
      groupId,
    };
  });

exports.publishMindmap = functions
  .region(REGION)
  .runWith({ timeoutSeconds: 60, memory: '256MB' })
  .https.onCall(async (data, context) => {
    if (!context.auth?.uid) {
      throw new functions.https.HttpsError('unauthenticated', 'Authentication required.');
    }

    const uid = context.auth.uid;
    const classId = String(data?.classId || '').trim();
    const subjectId = String(data?.subjectId || '').trim();
    const topic = String(data?.topic || '').trim();
    const depthLevel = String(data?.depthLevel || 'Medium').trim();
    const learningStyle = String(data?.learningStyle || 'Concept Based').trim();
    const topicCount = Number(data?.topicCount || 4);
    const structure = data?.structure;

    if (!classId || !subjectId || !topic) {
      throw new functions.https.HttpsError('invalid-argument', 'classId, subjectId and topic are required.');
    }
    if (!structure || typeof structure !== 'object') {
      throw new functions.https.HttpsError('invalid-argument', 'structure is required.');
    }

    const userDoc = await db.collection('users').doc(uid).get();
    const userData = userDoc.data() || {};
    const userRole = String(userData.role || '').toLowerCase();
    if (userRole !== 'teacher') {
      throw new functions.https.HttpsError('permission-denied', 'Only teachers can publish mindmaps.');
    }

    const classDoc = await db.collection('classes').doc(classId).get();
    if (!classDoc.exists) {
      throw new functions.https.HttpsError('not-found', 'Class not found.');
    }

    const classData = classDoc.data() || {};
    const standard = String(classData.className || '').trim();
    const section = String(classData.section || '').trim();
    const subjects = classData.subjects;
    let subjectName = subjectId;
    if (Array.isArray(subjects)) {
      const found = subjects.find((s) => String(s || '').toLowerCase().replace(/\s+/g, '_') === subjectId.toLowerCase());
      if (found) {
        subjectName = String(found);
      }
    }

    const normalizedRoot = normalizeMindmapNode(structure);
    if (!normalizedRoot.title || normalizedRoot.title === 'Untitled') {
      normalizedRoot.title = topic;
    }

    const previewNodes = Array.isArray(normalizedRoot.children)
      ? normalizedRoot.children.slice(0, 4).map((n) => n.title)
      : [];

    const groupId = `${classId}_${subjectId}`;
    const mindmapRef = db.collection('group_mindmaps').doc();
    await mindmapRef.set({
      mindmap_id: mindmapRef.id,
      group_id: groupId,
      class_id: classId,
      subject_id: subjectId,
      standard,
      section,
      subject: subjectName,
      topic,
      json_structure: normalizedRoot,
      created_by: uid,
      created_at: admin.firestore.FieldValue.serverTimestamp(),
      depth_level: depthLevel,
      learning_style: learningStyle,
      topic_count: Number.isInteger(topicCount) ? topicCount : 4,
    });

    return {
      mindmapId: mindmapRef.id,
      topic,
      previewNodes,
      groupId,
    };
  });

/**
 * Firestore Trigger: Auto-assign website-created tests
 * When a document is created in `scheduledTests`, create per-student
 * assignments in `testResults` matching the exact structure used by the app
 * and the website (as provided).
 */
exports.onScheduledTestCreate = functions
  .region(REGION)
  .runWith(RUNTIME_OPTS)
  .firestore.document('scheduledTests/{testId}')
  .onCreate(async (snap, context) => {
    const testId = context.params.testId;
    const data = snap.data() || {};

    try {
      // SAFETY: Skip auto-assignment for AI revision or student-only tests.
      // These are directly assigned by automation and must remain isolated.
      const isAIRevision =
        data.isAIRevision === true ||
        String(data.testCategory || '').toLowerCase() === 'ai_revision' ||
        String(data.title || '').toLowerCase().includes('ai revision test') ||
        String(data.testTitle || '').toLowerCase().includes('ai revision test');
      const isStudentOnly =
        String(data.visibility || '').toLowerCase() === 'student_only' ||
        data.skipAutoAssign === true;

      if (isAIRevision || isStudentOnly) {
        console.log(`onScheduledTestCreate: Skipping auto-assign for isolated/system test ${testId}`);
        return null;
      }

      // Required fields from provided structure
      const className = data.className || data.class || '';
      const section = data.section || '';
      const schoolCode = data.schoolCode || '';
      const teacherId = data.teacherId || '';
      const teacherEmail = data.teacherEmail || '';
      const teacherName = data.teacherName || '';
      const date = data.date || '';
      const startTime = data.startTime || '';
      const duration = Number.isFinite(data.duration) ? data.duration : 0;
      const title = data.title || data.testTitle || 'Untitled';
      const subject = data.subject || '';
      const totalMarks = Number.isFinite(data.totalMarks) ? data.totalMarks : 0;
      const totalQuestions = Number.isFinite(data.questionCount)
        ? data.questionCount
        : Array.isArray(data.questions) ? data.questions.length : 0;

      if (!schoolCode || !className) {
        console.log(`onScheduledTestCreate: Missing schoolCode/className for ${testId}; skipping.`);
        return null;
      }

      // Find target students
      let q = db.collection('students')
        .where('schoolCode', '==', schoolCode)
        .where('className', '==', className);
      if (section) q = q.where('section', '==', section);
      const studentsSnap = await q.get();

      if (studentsSnap.empty) {
        console.log(`onScheduledTestCreate: No students found for ${className} ${section || ''}`);
        return null;
      }

      let created = 0;
      let skipped = 0;

      for (const stuDoc of studentsSnap.docs) {
        const stu = stuDoc.data() || {};
        const studentEmail = stu.email || stu.studentEmail || '';
        const studentName = stu.studentName || stu.name || '';
        if (!studentEmail) { skipped++; continue; }

        // Resolve auth uid from users collection
        const userQ = await db.collection('users')
          .where('email', '==', studentEmail)
          .limit(1)
          .get();
        if (userQ.empty) { skipped++; continue; }
        const studentId = userQ.docs[0].id;

        // Idempotency: skip if assignment exists
        const existQ = await db.collection('testResults')
          .where('testId', '==', testId)
          .where('studentId', '==', studentId)
          .limit(1)
          .get();
        if (!existQ.empty) { skipped++; continue; }

        const payload = {
          answers: [],
          assignedAt: admin.firestore.FieldValue.serverTimestamp(),
          className: className,
          correctAnswers: 0,
          createdAt: admin.firestore.FieldValue.serverTimestamp(),
          date: date,                 // string e.g. "2025-11-22"
          duration: duration,
          earnedPoints: 0,
          schoolCode: schoolCode,
          score: 0,
          section: section,
          startTime: startTime,       // string e.g. "16:23"
          startedAt: null,
          status: 'assigned',
          studentEmail: studentEmail,
          studentId: studentId,       // auth uid
          studentName: studentName,
          subject: subject,
          submittedAt: null,
          teacherEmail: teacherEmail,
          teacherId: teacherId,
          teacherName: teacherName,
          testId: testId,
          testTitle: title,
          timeTaken: 0,
          totalMarks: totalMarks,
          totalPoints: 0,
          totalQuestions: totalQuestions,
          updatedAt: admin.firestore.FieldValue.serverTimestamp(),
        };

        await db.collection('testResults').add(payload);
        created++;
      }

      console.log(`onScheduledTestCreate: testId=${testId} created=${created} skipped=${skipped}`);
      return null;
    } catch (err) {
      console.error('onScheduledTestCreate error:', err);
      return null;
    }
  });

// Import Cloud Function for R2 file uploads
const { uploadFileToR2 } = require('./uploadFileToR2');
exports.uploadFileToR2 = uploadFileToR2;

// Import Cloud Functions for announcement cleanup (cost optimization)
const { deleteExpiredAnnouncements, manualDeleteExpiredAnnouncements } = require('./deleteExpiredAnnouncements');
exports.deleteExpiredAnnouncements = deleteExpiredAnnouncements;
exports.manualDeleteExpiredAnnouncements = manualDeleteExpiredAnnouncements;

// Import Cloud Functions for media announcement auto-deletion (24 hour ephemeral media)
const { deleteExpiredMediaAnnouncements, hardDeleteOldMediaMessages } = require('./deleteExpiredMediaAnnouncements');
exports.deleteExpiredMediaAnnouncements = deleteExpiredMediaAnnouncements;
exports.hardDeleteOldMediaMessages = hardDeleteOldMediaMessages;

// Import Cloud Functions for institute announcement auto-deletion (24 hour ephemeral announcements)
const { deleteExpiredInstituteAnnouncements, deleteExpiredInstituteAnnouncementsManual } = require('./deleteExpiredInstituteAnnouncements');
exports.deleteExpiredInstituteAnnouncements = deleteExpiredInstituteAnnouncements;
exports.deleteExpiredInstituteAnnouncementsManual = deleteExpiredInstituteAnnouncementsManual;

// Import Cloud Functions for teacher announcement auto-deletion (24 hour ephemeral teacher announcements)
const { deleteExpiredTeacherAnnouncements, deleteExpiredTeacherAnnouncementsManual } = require('./deleteExpiredTeacherAnnouncements');
exports.deleteExpiredTeacherAnnouncements = deleteExpiredTeacherAnnouncements;
exports.deleteExpiredTeacherAnnouncementsManual = deleteExpiredTeacherAnnouncementsManual;

// Import Cloud Functions for push notifications
const { 
  sendChatNotification, 
  sendAssignmentNotification, 
  sendAnnouncementNotification,
  cleanupOldNotifications 
} = require('./notifications');
exports.sendChatNotification = sendChatNotification;
exports.sendAssignmentNotification = sendAssignmentNotification;
exports.sendAnnouncementNotification = sendAnnouncementNotification;
exports.cleanupOldNotifications = cleanupOldNotifications;

// Import Cloud Functions for automated AI revision protocol
const {
  trackWeeklyStudentErrors,
  weeklyRevisionSweep,
  generateSundayEveningRevisionTests,
} = require('./automatedRevisionProtocol');
exports.trackWeeklyStudentErrors = trackWeeklyStudentErrors;
exports.weeklyRevisionSweep = weeklyRevisionSweep;
exports.generateSundayEveningRevisionTests = generateSundayEveningRevisionTests;
