'use strict';
/**
 * Firebase Cloud Function: generateQuestions
 * - Callable function that proxies requests to the DeepSeek Chat Completions API
 * - API key is stored securely via: firebase functions:config:set deepseek.key="YOUR_KEY"
 * - Inputs: { topic: string, count: number }
 * - Output: JSON string (strict JSON) as generated by the model
 */

const functions = require('firebase-functions');
const admin = require('firebase-admin');
const axios = require('axios').default;

// Initialize Admin SDK once
try {
  admin.app();
} catch (e) {
  admin.initializeApp();
}
const db = admin.firestore();

// Region and runtime options
const REGION = 'us-central1';
const RUNTIME_OPTS = { timeoutSeconds: 60, memory: '256MB' };

/**
 * Build the exact prompt required by the client.
 */
function buildPrompt(topic, count) {
  return `Generate questions for a student test.

Topic: ${topic}
Total Questions: ${count}

Distribute the questions evenly across these three types:
1. Multiple Choice Questions (MCQ)
2. True or False
3. Match the Following

Return the output in pure JSON format ONLY, with NO explanations, no markdown, and no extra text.

The JSON structure must be exactly:

{
  "mcq": [
    {
      "question": "Question text",
      "options": ["Option A", "Option B", "Option C", "Option D"],
      "answer": 0
    }
  ],
  "true_false": [
    {
      "question": "Question text",
      "answer": true
    }
  ],
  "match_the_following": [
    {
      "question": "Match the items",
      "left": ["Item1", "Item2", "Item3", "Item4"],
      "right": ["Match1", "Match2", "Match3", "Match4"],
      "answer": { "Item1": "Match2", "Item2": "Match1", "Item3": "Match4", "Item4": "Match3" }
    }
  ]
}

Rules:
- Output only valid JSON.
- Do not include explanations or notes.`;
}

/**
 * Sanitize potential code fences and ensure it's plain JSON text.
 */
function sanitizeToJsonString(text) {
  if (typeof text !== 'string') return '';
  let out = text.trim();
  // remove ```json ... ``` or ``` ... ``` fences if present
  if (out.startsWith('```')) {
    out = out.replace(/^```json\n?/i, '').replace(/^```\n?/i, '').replace(/```\s*$/i, '').trim();
  }
  return out;
}

/**
 * Basic structure validation to catch obvious format issues early.
 */
function validateStructure(obj) {
  if (!obj || typeof obj !== 'object') return false;
  if (!Array.isArray(obj.mcq) || !Array.isArray(obj.true_false) || !Array.isArray(obj.match_the_following)) return false;
  return true;
}

exports.generateQuestions = functions
  .region(REGION)
  .runWith(RUNTIME_OPTS)
  .https.onCall(async (data, context) => {
    // Auth optional: you can restrict to authenticated teachers only if needed
    try {
      const topic = (data && data.topic ? String(data.topic) : '').trim();
      const count = Number(data && data.count);

      if (!topic) {
        throw new functions.https.HttpsError('invalid-argument', 'Missing required parameter: topic');
      }
      if (!Number.isInteger(count) || count < 3 || count > 100) {
        throw new functions.https.HttpsError('invalid-argument', 'Parameter "count" must be an integer between 3 and 100.');
      }

      const cfg = functions.config();
      const apiKey = cfg && cfg.deepseek && cfg.deepseek.key ? cfg.deepseek.key : '';
      if (!apiKey) {
        throw new functions.https.HttpsError(
          'failed-precondition',
          'DeepSeek API key is not set. Configure with: firebase functions:config:set deepseek.key="YOUR_KEY"'
        );
      }

      const prompt = buildPrompt(topic, count);

      // DeepSeek OpenAI-compatible endpoint
      const url = 'https://api.deepseek.com/v1/chat/completions';
      const payload = {
        model: 'deepseek-chat',
        messages: [
          { role: 'user', content: prompt }
        ],
        temperature: 0.7,
        max_tokens: 1800,
        // Enforce JSON-only output if supported
        response_format: { type: 'json_object' }
      };

      const headers = {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`
      };

      let response;
      try {
        response = await axios.post(url, payload, { headers, timeout: 30000 });
      } catch (err) {
        // Axios error handling
        const status = err.response ? err.response.status : null;
        const body = err.response ? err.response.data : null;
        console.error('DeepSeek API error', { status, body, message: err.message });
        if (status === 429) {
          throw new functions.https.HttpsError('resource-exhausted', 'Rate limited by DeepSeek API. Please retry later.');
        }
        if (status === 401 || status === 403) {
          throw new functions.https.HttpsError('permission-denied', 'Invalid DeepSeek API key or insufficient permissions.');
        }
        throw new functions.https.HttpsError('unavailable', 'Failed to reach DeepSeek API.');
      }

      if (!response || response.status < 200 || response.status >= 300 || !response.data) {
        throw new functions.https.HttpsError('internal', 'Unexpected response from DeepSeek API.');
      }

      const choices = response.data.choices;
      if (!choices || !Array.isArray(choices) || choices.length === 0) {
        throw new functions.https.HttpsError('internal', 'No choices returned by DeepSeek API.');
      }

      const contentRaw = choices[0]?.message?.content ?? '';
      const jsonText = sanitizeToJsonString(contentRaw);

      // Validate JSON parses
      let parsed;
      try {
        parsed = JSON.parse(jsonText);
      } catch (e) {
        console.error('JSON parse failed. Content:', jsonText);
        throw new functions.https.HttpsError('data-loss', 'Model returned invalid JSON. Please retry.');
      }

      // Basic structure validation
      if (!validateStructure(parsed)) {
        throw new functions.https.HttpsError('failed-precondition', 'Model returned JSON in unexpected structure.');
      }

      // Return the JSON STRING (as required) back to Flutter
      return JSON.stringify(parsed);
    } catch (error) {
      if (error instanceof functions.https.HttpsError) {
        throw error;
      }
      console.error('Unhandled error in generateQuestions:', error);
      throw new functions.https.HttpsError('internal', 'Unexpected error.');
    }
  });

/**
 * Firestore Trigger: Auto-assign website-created tests
 * When a document is created in `scheduledTests`, create per-student
 * assignments in `testResults` matching the exact structure used by the app
 * and the website (as provided).
 */
exports.onScheduledTestCreate = functions
  .region(REGION)
  .runWith(RUNTIME_OPTS)
  .firestore.document('scheduledTests/{testId}')
  .onCreate(async (snap, context) => {
    const testId = context.params.testId;
    const data = snap.data() || {};

    try {
      // Required fields from provided structure
      const className = data.className || data.class || '';
      const section = data.section || '';
      const schoolCode = data.schoolCode || '';
      const teacherId = data.teacherId || '';
      const teacherEmail = data.teacherEmail || '';
      const teacherName = data.teacherName || '';
      const date = data.date || '';
      const startTime = data.startTime || '';
      const duration = Number.isFinite(data.duration) ? data.duration : 0;
      const title = data.title || data.testTitle || 'Untitled';
      const subject = data.subject || '';
      const totalMarks = Number.isFinite(data.totalMarks) ? data.totalMarks : 0;
      const totalQuestions = Number.isFinite(data.questionCount)
        ? data.questionCount
        : Array.isArray(data.questions) ? data.questions.length : 0;

      if (!schoolCode || !className) {
        console.log(`onScheduledTestCreate: Missing schoolCode/className for ${testId}; skipping.`);
        return null;
      }

      // Find target students
      let q = db.collection('students')
        .where('schoolCode', '==', schoolCode)
        .where('className', '==', className);
      if (section) q = q.where('section', '==', section);
      const studentsSnap = await q.get();

      if (studentsSnap.empty) {
        console.log(`onScheduledTestCreate: No students found for ${className} ${section || ''}`);
        return null;
      }

      let created = 0;
      let skipped = 0;

      for (const stuDoc of studentsSnap.docs) {
        const stu = stuDoc.data() || {};
        const studentEmail = stu.email || stu.studentEmail || '';
        const studentName = stu.studentName || stu.name || '';
        if (!studentEmail) { skipped++; continue; }

        // Resolve auth uid from users collection
        const userQ = await db.collection('users')
          .where('email', '==', studentEmail)
          .limit(1)
          .get();
        if (userQ.empty) { skipped++; continue; }
        const studentId = userQ.docs[0].id;

        // Idempotency: skip if assignment exists
        const existQ = await db.collection('testResults')
          .where('testId', '==', testId)
          .where('studentId', '==', studentId)
          .limit(1)
          .get();
        if (!existQ.empty) { skipped++; continue; }

        const payload = {
          answers: [],
          assignedAt: admin.firestore.FieldValue.serverTimestamp(),
          className: className,
          correctAnswers: 0,
          createdAt: admin.firestore.FieldValue.serverTimestamp(),
          date: date,                 // string e.g. "2025-11-22"
          duration: duration,
          earnedPoints: 0,
          schoolCode: schoolCode,
          score: 0,
          section: section,
          startTime: startTime,       // string e.g. "16:23"
          startedAt: null,
          status: 'assigned',
          studentEmail: studentEmail,
          studentId: studentId,       // auth uid
          studentName: studentName,
          subject: subject,
          submittedAt: null,
          teacherEmail: teacherEmail,
          teacherId: teacherId,
          teacherName: teacherName,
          testId: testId,
          testTitle: title,
          timeTaken: 0,
          totalMarks: totalMarks,
          totalPoints: 0,
          totalQuestions: totalQuestions,
          updatedAt: admin.firestore.FieldValue.serverTimestamp(),
        };

        await db.collection('testResults').add(payload);
        created++;
      }

      console.log(`onScheduledTestCreate: testId=${testId} created=${created} skipped=${skipped}`);
      return null;
    } catch (err) {
      console.error('onScheduledTestCreate error:', err);
      return null;
    }
  });

