import 'badge_model.dart';

const List<Badge> badgeMasterList = <Badge>[
  Badge(
    id: 'perfect_score',
    title: 'Perfect Score',
    description: 'Scored 100% in a test.',
    emoji: '🎯',
    category: 'test',
  ),
  Badge(
    id: 'high_scorer',
    title: 'High Scorer',
    description: 'Scored 90% or above in a test.',
    emoji: '🏆',
    category: 'test',
  ),
  Badge(
    id: 'excellent_scorer',
    title: 'Excellent Scorer',
    description: 'Scored 80% or above in a test.',
    emoji: '⭐',
    category: 'test',
  ),
  Badge(
    id: 'most_improved',
    title: 'Most Improved',
    description: 'Improved test score by 15% or more.',
    emoji: '📈',
    category: 'improvement',
  ),
  Badge(
    id: 'consistent_performer',
    title: 'Consistent Performer',
    description: 'Three tests with 75%+ scores.',
    emoji: '🧠',
    category: 'streak',
  ),
  Badge(
    id: 'test_streak_5',
    title: 'Test Streak (5)',
    description: 'Completed 5 tests without a break.',
    emoji: '🔥',
    category: 'streak',
  ),
  Badge(
    id: 'first_test',
    title: 'First Test',
    description: 'Completed your first test.',
    emoji: '🚀',
    category: 'milestone',
  ),
  Badge(
    id: 'fifth_test',
    title: 'Fifth Test',
    description: 'Completed five tests.',
    emoji: '🏅',
    category: 'milestone',
  ),
  Badge(
    id: 'tenth_test',
    title: 'Tenth Test',
    description: 'Completed ten tests.',
    emoji: '🥇',
    category: 'milestone',
  ),
  Badge(
    id: 'master_quizzer',
    title: 'Master Quizzer',
    description: 'Top score in a quiz or contest.',
    emoji: '🧩',
    category: 'quiz',
  ),
  Badge(
    id: 'quiz_streak_7',
    title: 'Quiz Streak (7)',
    description: 'Completed quizzes 7 days in a row.',
    emoji: '📅',
    category: 'quiz',
  ),
  Badge(
    id: 'first_challenge',
    title: 'First Challenge',
    description: 'Completed your first daily challenge.',
    emoji: '💪',
    category: 'challenge',
  ),
  Badge(
    id: 'streak_3',
    title: '3-Day Streak',
    description: 'Completed daily challenges for 3 days.',
    emoji: '🔥',
    category: 'challenge',
  ),
  Badge(
    id: 'streak_5',
    title: '5-Day Streak',
    description: 'Completed daily challenges for 5 days.',
    emoji: '🔥',
    category: 'challenge',
  ),
  Badge(
    id: 'streak_7',
    title: '7-Day Streak',
    description: 'Completed daily challenges for 7 days.',
    emoji: '🔥',
    category: 'challenge',
  ),
  Badge(
    id: 'fast_solver',
    title: 'Fast Solver',
    description: 'Solved a challenge very quickly.',
    emoji: '⚡',
    category: 'challenge',
  ),
  Badge(
    id: 'high_accuracy',
    title: 'High Accuracy',
    description: 'Achieved 90%+ accuracy in challenges.',
    emoji: '🎯',
    category: 'challenge',
  ),
  Badge(
    id: 'focus_30',
    title: 'Focus: 30min',
    description: 'Completed a 30-minute focused study timer.',
    emoji: '⏱️',
    category: 'productivity',
  ),
  Badge(
    id: 'focus_master',
    title: 'Focus Master',
    description: 'Accumulated 10 hours of focused study.',
    emoji: '🧘',
    category: 'productivity',
  ),
  Badge(
    id: 'homework_hero',
    title: 'Homework Hero',
    description: 'Submitted an assignment before deadline.',
    emoji: '📚',
    category: 'submission',
  ),
  Badge(
    id: 'punctual_student',
    title: 'Punctual Student',
    description: 'Checked in on time for all classes this week.',
    emoji: '⏰',
    category: 'attendance',
  ),
  Badge(
    id: 'perfect_attendance',
    title: 'Perfect Attendance',
    description: 'Full attendance for a month.',
    emoji: '📆',
    category: 'attendance',
  ),
  Badge(
    id: 'helpful_peer',
    title: 'Helpful Peer',
    description: 'Answered or helped a classmate (upvoted).',
    emoji: '🤝',
    category: 'community',
  ),
  Badge(
    id: 'teacher_favorite',
    title: 'Teacher\'s Pick',
    description: 'Nominated by a teacher for excellence or help.',
    emoji: '🏅',
    category: 'recognition',
  ),
  Badge(
    id: 'community_builder',
    title: 'Community Builder',
    description: 'Created a community or started an active thread.',
    emoji: '🏗️',
    category: 'community',
  ),
  Badge(
    id: 'resource_sharer',
    title: 'Resource Sharer',
    description: 'Shared useful notes or material used by peers.',
    emoji: '📎',
    category: 'community',
  ),
  Badge(
    id: 'discussion_leader',
    title: 'Discussion Leader',
    description: 'Started a discussion with high engagement.',
    emoji: '🗣️',
    category: 'community',
  ),
  Badge(
    id: 'project_finisher',
    title: 'Project Finisher',
    description: 'Completed a major project or group assignment.',
    emoji: '📁',
    category: 'milestone',
  ),
  Badge(
    id: 'coding_streak',
    title: 'Coding Streak',
    description: 'Completed daily coding tasks consecutively.',
    emoji: '💻',
    category: 'coding',
  ),
  Badge(
    id: 'contest_winner',
    title: 'Contest Winner',
    description: 'Won a competition or hackathon.',
    emoji: '🏆',
    category: 'competition',
  ),
  Badge(
    id: 'creative_thinker',
    title: 'Creative Thinker',
    description: 'Delivered a creative solution or project.',
    emoji: '🎨',
    category: 'creativity',
  ),
  Badge(
    id: 'presentation_pro',
    title: 'Presentation Pro',
    description: 'Gave a well-rated presentation.',
    emoji: '🎤',
    category: 'skill',
  ),
  Badge(
    id: 'badge_collector_10',
    title: 'Badge Collector (10)',
    description: 'Collected 10 badges in total.',
    emoji: '📦',
    category: 'milestone',
  ),
  Badge(
    id: 'badge_collector_25',
    title: 'Badge Collector (25)',
    description: 'Collected 25 badges in total.',
    emoji: '🎁',
    category: 'milestone',
  ),
  Badge(
    id: 'mentor_helper',
    title: 'Mentor Helper',
    description: 'Actively mentored or tutored peers multiple times.',
    emoji: '🧑‍🏫',
    category: 'community',
  ),
  Badge(
    id: 'feedback_hero',
    title: 'Feedback Hero',
    description: 'Provided constructive feedback used by others.',
    emoji: '✍️',
    category: 'community',
  ),
  Badge(
    id: 'challenge_master',
    title: 'Challenge Master',
    description: 'Completed 100 daily challenges.',
    emoji: '🏅',
    category: 'challenge',
  ),
  Badge(
    id: 'weekly_champion',
    title: 'Weekly Champion',
    description: 'Highest points in class this week.',
    emoji: '🥇',
    category: 'competition',
  ),
  Badge(
    id: 'monthly_champion',
    title: 'Monthly Champion',
    description: 'Top points in class this month.',
    emoji: '🏆',
    category: 'competition',
  ),
  Badge(
    id: 'social_butterfly',
    title: 'Social Butterfly',
    description: 'Joined and participated in multiple communities.',
    emoji: '🦋',
    category: 'community',
  ),
  Badge(
    id: 'rule_keeper',
    title: 'Rule Keeper',
    description: 'Exemplary conduct and discipline.',
    emoji: '🤝',
    category: 'behavior',
  ),
  Badge(
    id: 'eco_champion',
    title: 'Eco Champion',
    description: 'Participated actively in environment drives.',
    emoji: '🌱',
    category: 'activity',
  ),
  Badge(
    id: 'volunteer_star',
    title: 'Volunteer Star',
    description: 'Volunteered repeatedly in school activities.',
    emoji: '🤲',
    category: 'activity',
  ),
  Badge(
    id: 'reward_redeemer',
    title: 'Reward Redeemer',
    description: 'Successfully redeemed a reward.',
    emoji: '🎁',
    category: 'rewards',
  ),
  Badge(
    id: 'parent_approved',
    title: 'Parent Approved',
    description: 'Parent approved your reward request.',
    emoji: '✅',
    category: 'rewards',
  ),
  Badge(
    id: 'leaderboard_top10',
    title: 'Top 10 Leaderboard',
    description: 'Ranked in the class top 10.',
    emoji: '🏅',
    category: 'competition',
  ),
  Badge(
    id: 'study_night',
    title: 'Study Night',
    description: 'Completed a verified late-night study session.',
    emoji: '🌙',
    category: 'productivity',
  ),
  Badge(
    id: 'rapid_respondent',
    title: 'Rapid Respondent',
    description: 'Quick reply rate in class forum or Q&A.',
    emoji: '⚡',
    category: 'engagement',
  ),
  Badge(
    id: 'exam_preparer',
    title: 'Exam Preparer',
    description: 'Completed syllabus revision before an exam.',
    emoji: '📘',
    category: 'milestone',
  ),
  Badge(
    id: 'collaboration_champion',
    title: 'Collaboration Champion',
    description: 'Significant contribution in group work.',
    emoji: '🤝',
    category: 'teamwork',
  ),
];
