import 'badge_model.dart';

const List<Badge> badgeMasterList = <Badge>[
  Badge(
    id: 'perfect_score',
    title: 'Perfect Score',
    description: 'Scored 100% in a test',
    emoji: '🎯',
    category: 'test',
    points: 150,
  ),
  Badge(
    id: 'high_scorer',
    title: 'High Scorer',
    description: 'Scored 90% or above in a test',
    emoji: '🏆',
    category: 'test',
    points: 120,
  ),
  Badge(
    id: 'excellent_scorer',
    title: 'Excellent Scorer',
    description: 'Scored 80% or above in a test',
    emoji: '⭐',
    category: 'test',
    points: 100,
  ),
  Badge(
    id: 'most_improved',
    title: 'Most Improved',
    description: 'Improved test score by 15% or more',
    emoji: '📈',
    category: 'improvement',
    points: 110,
  ),
  Badge(
    id: 'consistent_performer',
    title: 'Consistent Performer',
    description: 'Three tests with 75%+ scores',
    emoji: '🧠',
    category: 'streak',
    points: 90,
  ),
  Badge(
    id: 'test_streak_5',
    title: 'Test Streak',
    description: 'Completed 5 tests without a break',
    emoji: '🔥',
    category: 'streak',
    points: 80,
  ),
  Badge(
    id: 'first_test',
    title: 'First Test',
    description: 'Completed your first test',
    emoji: '🚀',
    category: 'milestone',
    points: 50,
  ),
  Badge(
    id: 'fifth_test',
    title: 'Fifth Test',
    description: 'Completed five tests',
    emoji: '🏅',
    category: 'milestone',
    points: 70,
  ),
  Badge(
    id: 'tenth_test',
    title: 'Tenth Test',
    description: 'Completed ten tests',
    emoji: '🥇',
    category: 'milestone',
    points: 100,
  ),
  // Daily challenges
  Badge(
    id: 'first_challenge',
    title: 'First Challenge',
    description: 'Completed your first daily challenge',
    emoji: '💪',
    category: 'challenge',
    points: 40,
  ),
  Badge(
    id: 'streak_3',
    title: '3-Day Streak',
    description: 'Completed daily challenges for 3 days',
    emoji: '🔥',
    category: 'challenge',
    points: 60,
  ),
  Badge(
    id: 'streak_5',
    title: '5-Day Streak',
    description: 'Completed daily challenges for 5 days',
    emoji: '🔥',
    category: 'challenge',
    points: 80,
  ),
  Badge(
    id: 'streak_7',
    title: '7-Day Streak',
    description: 'Completed daily challenges for 7 days',
    emoji: '🔥',
    category: 'challenge',
    points: 120,
  ),
  Badge(
    id: 'fast_solver',
    title: 'Fast Solver',
    description: 'Solved a challenge very quickly',
    emoji: '⚡',
    category: 'challenge',
    points: 90,
  ),
  Badge(
    id: 'high_accuracy',
    title: 'High Accuracy',
    description: 'Achieved 90%+ accuracy in challenges',
    emoji: '🎯',
    category: 'challenge',
    points: 100,
  ),
];
